variables:
  agentPool: 'AwsHMG'
  agentType: 'net5'
  buildConfiguration: 'Release'

stages: 
- stage: SpinUpAgent
  pool:
      name: $(agentPool)
      
  jobs: 
      - job: SpinupAgent
        displayName: Spining up Agent
        steps:
          - checkout: none
          - script: helm install --namespace $(agentPool) --wait $(agentType)-$(Build.BuildId) --set agent.type=$(agentType) --set pipelines.url=https://dev.azure.com/alm-animaeducacao --set pipelines.pat=b5kqhw7adz423g7pjt77tud3tzwhapynggvz3rpdbcdj4fwmmbxa emberstack/azure-pipelines-agent
            displayName: "Create an Agent- HELM"
            
- stage: Build
  pool:
      name: $(agentPool)
      demands:
      - Agent.Name -equals $(agentType)-$(Build.BuildId)
  
  jobs: 
      - job: UseNETCore
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 5.0.101'
            inputs:
               packageType: 'sdk'
               version: '5.0.101'
               includePreviewVersions: true

      - job: BuildNetCore
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build .NET Core 5'
            inputs:
               command: build
               projects: '**/*.csproj'
               arguments: '--configuration $(buildConfiguration)' # Update this to match your need)'
  
- stage: DeleteAgent
  pool:
      name: $(agentPool)

  jobs:
    - job: HelmUninstall
      steps:
        - checkout: none
        - script: |
            helm uninstall --namespace $(agentPool) $(agentType)-$(Build.BuildId)
          displayName: "Delete an Agent - HELM"
