variables:
  project: 'teste-net5'
  agentPool: 'AwsHMG4'
  agentType: 'net5'
  buildConfiguration: 'Release'

stages: 
      
- stage: Build
  pool:
      name: $(agentPool)
      demands:
      - Agent.OSArchitecture -equals X64
  
  jobs: 
      - job: NETCore
        steps:
          - task: UseDotNet@2
            displayName: '.NET Core sdk 5.0.101'
            inputs:
               packageType: 'sdk'
               version: '5.0.101'
               includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'Build .NET Core 5'
            inputs:
               command: build
               projects: '**/*.csproj'
               arguments: '--configuration $(buildConfiguration)' # Update this to match your need)'
  
